version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada
    restart: always
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - ENTRADA_NAMESERVERS=
      
      # PostgreSQL config options, make sure the the database is created before 
      # starting the container
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # AWS config options for S3 and Athena
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_KEY=
      # configure bucket name, entrada will create and configure bucket 
      - AWS_BUCKET=entrada-data-myorg
      # override output location with an s3 location
      - ENTRADA_LOCATION_OUTPUT=s3://entrada-data-myorg/database/
       
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - ENTRADA_ENGINE=aws
      - JAVA_OPTS=-Xmx4g -Xms4g
      # Map internal container path to a path on the host
      # format <host-path>:<container:path>
      # ENTRADA will write to /entrada/... in the container
    volumes:
      - ./:/entrada/data/
    dns: 
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"
