version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:<tag>
    restart: always
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - ENTRADA_NAMESERVERS=
      
      # PostgreSQL config options, make sure the the database is created before
      # starting the container
      # replace <host_or_ip> with the actual host of ip, do not use localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://<host_or_ip>:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # Hadoop ( copy core-site.xml and hdfs-site.xml to the conf dir)
      - HDFS_NAMESERVICE_HOST=namenode.example.com
      - IMPALA_DAEMON_HOST=impalad.example.com
      - ENTRADA_LOCATION_OUTPUT=hdfs://namenode.example.com:8020/user/entrada/database
      - HDFS_USERNAME=hdfs
      
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - ENTRADA_ENGINE=hadoop
      - JAVA_OPTS=-Xmx4g -Xms4g
      # Map internal container path to a path on the host
      # format <host-path>:<container:path>
      # ENTRADA will write to /entrada/... in the container
    volumes:
      - ./:/entrada/data/
    dns:
      - 8.8.8.8
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"